name: razorpay_totalxsoftware
description: "RazorpayTotalxsoftware is a Flutter package for quick and easy Razorpay integration with optional Firebase transaction logging. Perfect for smooth in-app payments."
version: 1.0.1
homepage: https://github.com/totalxsoftwaredevelopers/razorpay_totalxsoftware

environment:
  sdk: ^3.5.3
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  cloud_firestore: ^5.4.4
  uuid: ^4.5.1
  intl: ^0.19.0
  http: ^1.2.2
  gap: ^3.0.1
  razorpay_flutter: ^1.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  assets:
    - assets/

  plugin:
    platforms:
    android:
    ios:

screenshots:
  - description: "www.totalx.in"
    path: assets/images/totalx.png
